apiVersion: v1
kind: ConfigMap
metadata:
  name: liveness-script
data:
  liveness.sh: |
    #!/bin/sh
    peers=$(curl -H "Content-Type: application/json" -X POST --data '{"jsonrpc":"2.0","method":"net_peerCount","params":[],"id":3}' --silent localhost:18545 | jq .result)
    if [[ $peers != "0x0" ]];then
        exit 0
    else
        exit 1
    fi