apiVersion: v1
kind: Service
metadata:
  name: fantom-node
  labels:
    app: {{ template "app.fullname" . }}
    chart: {{ template "app.chart" . }}
    release: {{ .Release.Name }}
    app.kubernetes.io/instance: fantom-node
    app.kubernetes.io/name: fantom-node
    app.kubernetes.io/part-of: chain-fantom
    app.kubernetes.io/role: fantom
    chain: fantom
    network: {{ .Values.network }}
spec:
  ports:
  - name: p2p
    protocol: TCP
    port: 5050
    targetPort: 5050
  - name: monitoring
    protocol: TCP
    port: 6060
    targetPort: 6060
  - name: fantom-rpc
    protocol: TCP
    port: 18545
    targetPort: 18545
  - name: fantom-ws
    protocol: TCP
    port: 18546
    targetPort: 18546
  selector:
    app.kubernetes.io/instance: fantom-node
    app.kubernetes.io/name: fantom-node
    app.kubernetes.io/part-of: chain-fantom
  type: ClusterIP